[build]
  command = "hugo"
  publish = "public"
  

[build.environment]
  HUGO_VERSION = "0.88.1"
  HUGO_ENV = "production"
[[headers]]
  for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"

